### ISSUE TITLE
Create step that will go out from scope.

### ISSUE THREAD

**Issue by Naastya** [BR0kEN-/behat-drupal-propeople-context#2]
I faced with a problem that when you test one region, appears need to move another region. For now there is just step "I work with elements in region". It is possible to re-use this step, but logical it would more logical to have step which allows to go out from region.

**Comment by BR0kEN-** [comment]
Hi, Nastya.

I've agreed with you and added the new step - `I checkout to whole page` - in a [1.2.1 version](https://github.com/BR0kEN-/behat-drupal-propeople-context/tree/1.2.1).
