### ISSUE TITLE
Make please custom step for hierarchical select 

### ISSUE THREAD

**Issue by Naastya** [BR0kEN-/behat-drupal-propeople-context#5]
On one project I faced with the problem that one select has "display:none" attribute. Behat doesn't work with invisible elements. This select is implemented in [Hierarchical Select](https://www.drupal.org/project/hierarchical_select) drupal module. There is a tree of selects and first of them is invisible. Behat tries to get this first select and my tests are failed.

**Comment by BR0kEN-** [comment]
You can update the framework to [1.2.3](https://github.com/BR0kEN-/behat-drupal-propeople-context/tree/1.2.3) version and use the next step:

``` gherkin
And select the following in "Categories" hierarchical select:
  | EN                  |
  | Financial Services  |
```

This step will works for: [Hierarchical Select](https://www.drupal.org/project/hierarchical_select), [Simple Hierarchical Select](https://www.drupal.org/project/shs) and [Clientside Simple Hierarchical Select](https://www.drupal.org/project/cshs).
